version: '3.8'

services:
  backend:
    build: backend
    depends_on:
      - db
    ports:
      - 8080:8080

  db:
    build: 
      context: .
      dockerfile: DB_Dockerfile
    volumes:
      - ./database:/var/lib/postgresql/data

volumes:
  pgdata:
