services:
  backend:
    container_name: backend
    build: backend
    depends_on:
      - db
    ports:
      - 8080:8080

  db:
    container_name: db
    build: 
      context: .
      dockerfile: DB_Dockerfile
    volumes:
      - ./database:/var/lib/postgresql/data
      